sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - "https://github.com/hamcrest/JavaHamcrest/hamcrest-all|https://github.com/hamcrest/JavaHamcrest"
build:
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "8.26.0"
    - "7.1.26"
excludes:
  - "E-PK-CORE-17: Missing required file: 'release_config.yml'"
