sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
build:
  runnerOs: ubuntu-24.04
  exasolDbVersions:
    - "8.34.0"
    # UDFs in Exasol 7.1 with Ubuntu 20.04 will be fixed in the next Docker-DB release
    # - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
