sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
linkReplacements:
  - "https://github.com/hamcrest/JavaHamcrest/hamcrest-all|https://github.com/hamcrest/JavaHamcrest"