sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
build:
  # UDFs in Exasol 7.1 require Ubuntu 20.04
  runnerOs: ubuntu-20.04
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
